// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseAside: typeof import('./components/base/BaseAside.vue')['default']
    BaseFooter: typeof import('./components/base/BaseFooter.vue')['default']
    BaseHeader: typeof import('./components/base/BaseHeader.vue')['default']
    CommentControl: typeof import('./components/dashboard/CommentControl.vue')['default']
    CommentTable: typeof import('./components/dashboard/CommentTable.vue')['default']
    CommentToolbar: typeof import('./components/dashboard/CommentToolbar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemBadge: typeof import('./components/internal/SystemBadge.vue')['default']
    UpdatePassword: typeof import('./components/user/UpdatePassword.vue')['default']
    UpdateProfile: typeof import('./components/user/UpdateProfile.vue')['default']
    WalineClient: typeof import('./components/WalineClient.vue')['default']
    WithGithub: typeof import('./components/features/WithGithub.vue')['default']
  }
}
