// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseAside: typeof import('./components/base/BaseAside.vue')['default']
    BaseFooter: typeof import('./components/base/BaseFooter.vue')['default']
    BaseHeader: typeof import('./components/base/BaseHeader.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    CommentTable: typeof import('./components/dashboard/CommentTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Footer: typeof import('./components/Footer.vue')['default']
    ICarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    ICarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    ICarbonLanguage: typeof import('~icons/carbon/language')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    ICarbonWarning: typeof import('~icons/carbon/warning')['default']
    IMdiExitToApp: typeof import('~icons/mdi/exit-to-app')['default']
    IMdiLogin: typeof import('~icons/mdi/login')['default']
    IRiDashboardLine: typeof import('~icons/ri/dashboard-line')['default']
    IRiDiscussLine: typeof import('~icons/ri/discuss-line')['default']
    IRiFileInfoLine: typeof import('~icons/ri/file-info-line')['default']
    IRiGithubLine: typeof import('~icons/ri/github-line')['default']
    IRiHome2Line: typeof import('~icons/ri/home2-line')['default']
    IRiHomeLine: typeof import('~icons/ri/home-line')['default']
    IRiLanguageLine: typeof import('~icons/ri/language-line')['default']
    IRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IRiSunLine: typeof import('~icons/ri/sun-line')['default']
    IRiTranslate: typeof import('~icons/ri/translate')['default']
    IRiTranslateLine: typeof import('~icons/ri/translate-line')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
