// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseAside: typeof import('./components/base/BaseAside.vue')['default']
    BaseFooter: typeof import('./components/base/BaseFooter.vue')['default']
    BaseHeader: typeof import('./components/base/BaseHeader.vue')['default']
    CommentControl: typeof import('./components/dashboard/CommentControl.vue')['default']
    CommentTable: typeof import('./components/dashboard/CommentTable.vue')['default']
    CommentToolbar: typeof import('./components/dashboard/CommentToolbar.vue')['default']
    ICarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    ILogosMicrosoftEdge: typeof import('~icons/logos/microsoft-edge')['default']
    IMdiExitToApp: typeof import('~icons/mdi/exit-to-app')['default']
    IMdiLogin: typeof import('~icons/mdi/login')['default']
    IRiAndroidLine: typeof import('~icons/ri/android-line')['default']
    IRiAppleLine: typeof import('~icons/ri/apple-line')['default']
    IRiChromeLine: typeof import('~icons/ri/chrome-line')['default']
    IRiCpuLine: typeof import('~icons/ri/cpu-line')['default']
    IRiDashboardLine: typeof import('~icons/ri/dashboard-line')['default']
    IRiDeleteBinLine: typeof import('~icons/ri/delete-bin-line')['default']
    IRiDiscussLine: typeof import('~icons/ri/discuss-line')['default']
    IRiFileInfoLine: typeof import('~icons/ri/file-info-line')['default']
    IRiFirefoxLine: typeof import('~icons/ri/firefox-line')['default']
    IRiGithubLine: typeof import('~icons/ri/github-line')['default']
    IRiHome2Line: typeof import('~icons/ri/home2-line')['default']
    IRiLink: typeof import('~icons/ri/link')['default']
    IRiMacLine: typeof import('~icons/ri/mac-line')['default']
    IRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IRiPencilLine: typeof import('~icons/ri/pencil-line')['default']
    IRiRefreshLine: typeof import('~icons/ri/refresh-line')['default']
    IRiSafariLine: typeof import('~icons/ri/safari-line')['default']
    IRiSearchLine: typeof import('~icons/ri/search-line')['default']
    IRiSmartphoneLine: typeof import('~icons/ri/smartphone-line')['default']
    IRiSunLine: typeof import('~icons/ri/sun-line')['default']
    IRiTabletLine: typeof import('~icons/ri/tablet-line')['default']
    IRiTranslate: typeof import('~icons/ri/translate')['default']
    IRiUserLine: typeof import('~icons/ri/user-line')['default']
    IRiWindowLine: typeof import('~icons/ri/window-line')['default']
    IRiWindowsLine: typeof import('~icons/ri/windows-line')['default']
    ISimpleIconsLinux: typeof import('~icons/simple-icons/linux')['default']
    ISimpleIconsXiaomi: typeof import('~icons/simple-icons/xiaomi')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemBadge: typeof import('./components/internal/SystemBadge.vue')['default']
    UpdatePassword: typeof import('./components/user/UpdatePassword.vue')['default']
    UpdateProfile: typeof import('./components/user/UpdateProfile.vue')['default']
    WalineClient: typeof import('./components/WalineClient.vue')['default']
    WithGithub: typeof import('./components/features/WithGithub.vue')['default']
  }
}

export {}
